# Generated by Django 3.0.7 on 2020-12-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productDescription', models.CharField(max_length=1000)),
                ('productPrice', models.FloatField()),
                ('stars', models.IntegerField()),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='productImages')),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productsId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProductModel', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('paymentMethod', models.CharField(max_length=10)),
                ('paymentDone', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='api.Products', verbose_name='products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomUser', verbose_name='user')),
            ],
        ),
    ]
